[[main]]
  identifier = "about"
  name = "Intro N=1"
  url = "about"
  weight = 1

[[main]]
  identifier = "resources"
  name = "Resources"
  url = "resources"
  weight = 2

[[main]]
  identifier = "youtube"
  name = "Videos"
  url = "youtube"
  weight = 3

[[main]]
  identifier = ""
  name = ""
  url = ""
  weight = 4

[[main]]
  parent = ""
  name = ""
  url = ""

[[main]]
  parent = ""
  name = ""
  url = ""

[[main]]
  identifier = ""
  name = ""
  url = ""
  weight = 5

[[main]]
  identifier = ""
  name = ""
  url = ""
  weight = 6

[[main]]
  identifier = ""
  name = ""
  url = ""
  weight = 7
